"""Many-to-many update

Revision ID: 7fd80cfedb36
Revises: 
Create Date: 2024-11-28 12:54:15.999686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fd80cfedb36'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Login',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('password', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('race',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('competing', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('race', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_race_name'), ['name'], unique=True)

    op.create_table('user_race',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('race_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['race_id'], ['race.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['Login.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'race_id')
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_race')
    with op.batch_alter_table('race', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_race_name'))

    op.drop_table('race')
    op.drop_table('Login')
    # ### end Alembic commands ###
